#!/usr/bin/env bash
set -euo pipefail

cd /micropython-wrap/micropython
make -C mpy-cross

cd ports/stm32
make submodules
make BOARD=LEGO_HUB_NO6 clean
make BOARD=LEGO_HUB_NO6 submodules
make BOARD=LEGO_HUB_NO6

# vi: ft=sh

