#!/usr/bin/env bash
set -euo pipefail

# source ~/.asdf/asdf.sh
# cd /circuitpython-wrap
# ./bin/env/python-setup

cd /circuitpython-wrap/circuitpython

python3 -m venv /tmp/venv
source /tmp/venv/bin/activate

make fetch-all-submodules
pip install -r requirements-dev.txt
make -C mpy-cross

cd ports/stm
make fetch-port-submodules
make BOARD=feather_stm32f405_express

# vi: ft=sh
